### ISSUE TITLE
Troubles in multi_put function

### ISSUE THREAD

**Issue by yamas8** [griddb/python_client#12]
I met two troubles in multi-put function.
1. The multi_put function core dumped by giving name of no exist container as a key.
2. The memory allocation increases with multiple callings. I suspect it has memory leak.

**Comment by knonomura** [comment]
Thank you for your usage and information.
I will improve them.

**Comment by knonomura** [comment]
I modified two troubles in multi-put by acdae707338ee2a9c5a0e5cd035eb563c51e6028 and 1ca5d5614e75a151baa6d6b9a643bb3775515936 .
Please try the latest source code.

And I will continue to improve 0.8.

**Comment by yamas8** [comment]
I tested it briefly. It looks OK. 
Thank you.
