### ISSUE TITLE
Mederov Algorithm D optimal statistics 

### ISSUE THREAD

**Issue by ROHITKUMARBEHERA** [griddb/python_client#16]
Help me to write the Programme of Mederov Algorithm of D optimal statistics

**Comment by knonomura** [comment]
I close this issue as it is not related to this repository.

And I guess it might be useful for you to use stackoverflow.
https://stackoverflow.com/questions/14740373/design-of-experiments-doe-in-python
https://stackoverflow.com/questions/42860388/create-factor-in-a-data-frame-that-minimizes-correlation-with-other-variables-in
