### ISSUE TITLE
Coredump error when using put_container API

### ISSUE THREAD

**Issue by chiendh** [griddb/python_client#18]
We write a sample code which use put_container API. However, error coredump is occurred.
Detail environment is:
- Sever and Client : both in 1 machine CentOS 7.
- C Client : 4.3.0-1.linux (use rpm file in Github, at release page)
- GridDB Server : 4.3.0-36424 CE (use rpm file in Github, at release page)
- Python Client : use master branch in GitHub.
You can refer sample code in attached file
[sample_error.txt](https://github.com/griddb/python_client/files/4034547/sample_error.txt)

**Comment by knonomura** [comment]
Thank you so much for your usage, bug report and sample code.
I'll check it.

**Comment by knonomura** [comment]
I found this is an issue for C Client (griddb/c_client#15).
I'll fix it.

**Comment by knonomura** [comment]
I fixed this issue (griddb/c_client#15).
I'll release a new package for C Client.

**Comment by chiendh** [comment]
Thank you so much for feedback.
I'm waiting your release package for C client.

**Comment by chiendh** [comment]
Dear GridDB team,

I see you have released new C client (V.4.3.1) 
I have executed test.
It's OK now.
I closed issue.
